name: Auto-merge Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main  # Tylko PR-y, które kierują się na main

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'

    services:
      postgres:
        image: postgres:18.0-alpine3.22
        ports:
          - 5431:5432
        env:
          POSTGRES_PASSWORD: testpass
          POSTGRES_USER: testuser
          POSTGRES_DB: testdb
        options: >-
          --health-cmd="pg_isready -U testuser -d testdb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v5

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: run database migrations
        run: bun x prisma migrate deploy
        env:
          DATABASE_URL: postgres://testuser:testpass@localhost:5431/testdb

      - name: Install Postgres client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Run tests
        env:
          DATABASE_URL: postgres://testuser:testpass@localhost:5431/testdb
          CI: true
        run: bun test


      - name: Auto-merge PR
        if: success()
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge --auto
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
