on:
  workflow_dispatch: 
  push:
    branches:
      - main

jobs:
  generate-typedoc:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build TypeDoc documentation
        run: |
          bunx typedoc

      - name: Deploy TypeDoc
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html
          destination_dir: docs

  generate-schemaspy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    services:
      postgres:
        image: postgres:18.0-alpine3.22
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: schemaspy
          POSTGRES_USER: schemaspy
          POSTGRES_DB: postgres
        options: >-
          --health-cmd="pg_isready -U schemaspy -d postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
          --network-alias postgres

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run database migrations
        run: bun x prisma migrate deploy
        env:
          DATABASE_URL: postgres://schemaspy:schemaspy@localhost:5432/postgres

      - name: Prepare output directory
        run: |
          mkdir -p ./docs/schemaspy-output
          chmod -R 777 ./docs/schemaspy-output

      - name: Generate SchemaSpy documentation
        run: |
          docker run --rm \
            --user root \
            -v $(pwd)/docs/schemaspy-output:/output \
            --network host \
            schemaspy/schemaspy:latest \
            -debug \
            -t pgsql11 \
            -db postgres \
            -host localhost \
            -u schemaspy \
            -p schemaspy \
            -port 5432

      - name: Deploy SchemaSpy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/schemaspy-output
          destination_dir: database
